### ISSUE TITLE
Support for non chrome browsers

### ISSUE THREAD

**Issue by NicolasCARPi** [describo/web#1]
Hello,

What are you using as web technology that is only supported in Chromium based browsers? It seems you are artificially blocking Firefox users (or any user not using Chromium/Chrome) from using the software, so I'm interested in knowing what exactly prevents the web app from working with non-Chrome browsers.

As far as I know, there are very few things (if any) that are supported in Chromium and not Firefox, and in any case it shouldn't be ground for straight up banning everything that is not Chrome! (you don't even allow Edge that is based on Chromium and should work fine too!). If something is missing in the browser, workarounds can be found.

Maybe this made sense at the time, and now is the moment to remove this limitation, based on results from https://caniuse.com/. After all, it is a pretty straightforward and simple web application with html and javascript, so I really don't see why only Chrome should work.

Best,
~Nico

**Comment by marcolarosa** [comment]
hi @NicolasCARPi 

The reason for limiting the application to chrome browsers is because it uses the filesystem api. Specifically: https://caniuse.com/?search=showDirectoryPicker.

As it happens, I was working [on this very code yesterday](https://github.com/describo/web/commit/cec26699584a6a7da64ad4841b081c3def86302e) and changed it from checking for chrome to looking for the specific method I require in the window object. If you look at that commit you'll see that it checks for `showOpenFilePicker` in the window object, also a capability I was using (but since I'm not anymore, I will revise it soon to check for `showDirectoryPicker`). This change then allows the edge browser to be an option for people as well (and you'll notice in the commit I include a comment about edge).

In principle, this should work in all chromium based browsers but for reasons I can't explain, it doesn't work in the Brave browser which is chromium based.

To your points about explicitly excluding users; I myself am a firefox user.

Thankyou for asking the question but for future reference, I didn't appreciate the tone. I found it to be unnecessarily aggressive and threatening.

**Comment by NicolasCARPi** [comment]
Hello Marco,

Thank you for your complete explanation and sorry if I sounded aggressive. Communication and diplomaty aren't my strong points, thanks for letting me know about your feeling, I'll do better next time.

Best regards,
~Nico
